name: farmers_market
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0  <3.0.0"


dependencies:
  path_provider: ^2.0.11
  excel: ^1.1.5
  transparent_image: ^2.0.0
  carousel_pro: ^1.0.0
  fluttertoast: ^8.0.9
  dropdown_button2: ^1.6.3

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^1.19.1
  cloud_firestore: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - Categories.xlsx
   - images/splash.jpg
   - images/image1.jpg
   - images/image2.jpg
   - images/image3.jpg
   - images/image4.jpg
   - images/login_page.jpg
   - images/milk1.jpg
   - images/milk2.jpg
   - images/milk3.jpg
   - images/milk4.jpg
   - images/subsci.jpg
   - images/01.jpg
   - images/02.jpg
   - images/03.jpg
   - images/04.jpg
   - images/05.jpg
   - images/06.jpg
   - images/07.jpg
   - images/08.jpg
   - images/09.jpg
   - images/10.jpg
   - images/11.jpg
   - images/12.jpg
   - images/dalimb.jpg
   - images/coconut1.jpg
   - images/coconut2.jpg
   - images/banana.jpg
   - images/apple.jpg
   - images/subs_img.jpg
   - images/reserve.jpg
   - images/history.jpg
   - images/bill.jpg
   - images/balance.jpg





      # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gotham
      fonts:
        - asset: fonts/gotham_medium.OTF
        
          
  #  - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
